@baseUrl = http://localhost:3080/api
@resourceName = products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name fillterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=800000

###

# @name fillterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=pants

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=4

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

 {
    "categoryId": "40c3564c-0a30-48ec-ab28-cb285f4af90d",
    "name": "Electronic Steel Shoes",
    "description": "test update",
    "price": 500000,
    "image_url": ""
  }

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/DFewtAe
Content-Type: application/json

 {
    "name": "Electronic update",
    "description": "test update 12"
  }

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
